
stages:
  - maven-settings
  - npm-build
  - docker-build
#  - deploy

image: node:18.17.1
cache:
  paths:
    - www/

build:
  stage: npm-build
  script:
    - npm install
    - npm run build

build_image:
  stage: docker-build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASS}  registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/darkoum/admin-front:1.0 .
    - docker push registry.gitlab.com/darkoum/admin-front:1.0
