create table
  public."IMMO_MENU_ITEM" (
                            id bigint generated by default as identity,
                            immo_mnu_label character varying not null,
                            immo_mnu_link character varying not null,
                            immo_mnu_color character varying null,
                            immo_mnu_icon character varying not null,
                            immo_mnu_role smallint not null,
                            constraint IMMO_MENU_ITEM_pkey primary key (id)
) tablespace pg_default;


CREATE TABLE public.agence_01(
    agence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agence_name text NOT NULL,
    agence_email text NOT NULL UNIQUE,
    agence_status int NOT NULL DEFAULT 1,
    agence_metadata jsonb,
    CREATED_AT timestamp null default null with time zone DEFAULT CURRENT_TIMESTAMP,
    last_update timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FONCTION update_last_update_column()
RETURNS TRIGGER AS $$
BEGIN
    SET TIME ZONE 'CET';
    NEW.last_update = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;



CREATE TRIGGER set_last_update
BEFORE UPDATE ON public.agence_01
FOR EACH ROW
EXECUTE FONCTION update_last_update_column();



INSERT INTO public."IMMO_MENU_ITEM" (immo_mnu_label, immo_mnu_link, immo_mnu_icon, immo_mnu_color, immo_mnu_role)
VALUES
  ('HOME', 'home', 'house-fill', '#0C1425', 2),
  ('ACCOUNT', 'account', 'rocket-takeoff-fill', '#0C1425', 2),
  ('ANNOUNCE', 'announce', 'folder-fill', '#0C1425', 2),
  ('CALENDAR', 'calendar', 'calendar-fill', '#0C1425', 2),
  ('SETTINGS', 'settings', 'gear-wide', '#0C1425', 2),
  ('LOGOUT', 'logout', 'person', '#0C1425', 2);









